IDE::Toolbar proc createTrad {} {
    image create photo trad -data {
R0lGODlhFgAWAPIDAAAAADAwMMzMzP///8zMzAAAAAAAAAAAACH5BAEAAAQALAAAAAAWABYAAANX
SLrc/jDKGaq9gY7NeZbBgFXiOHZoiHZka4kbsLXl6s1yGr4kPADA2U4VAwIDRiNr+EsikzKXbVbM
eYZMX1A31dqkO2q39+3WpsSv6WL+QNIr92N9mUwSADs=
}
}
