IDE::Toolbar proc createPolando {} {
    image create photo polando -data {
R0lGODlhFgAWAPMHAAAAAMAAAP8AAP//AMzMzNzc3MD//////8zMzAAAAAAAAAAAAAAAAAAAAAAA
AAAAACH5BAEAAAgALAAAAAAWABYAAAReEMlJq7046837NEcojiJwgWQKAIWFpuXaVi+8ym4IqDeb
HytSz2f66IIhgXLZGjoBy6ig+exJmYiiJKC8XbEVrmA1KJvPM4oYcG6X0xOuew7fzumZgn7P33v+
gIEUEQA7
}
}
