IDE::System proc getXotclPackages {} {
 # I dont know any method to request the available xotcl packages
 return [split {xotcl::awo::htmlPlace
xotcl::awo::secureHtmlPlace
xotcl::awo::userMgt
xotcl::awo::webAgent
xotcl::awo::webDocument
xotcl::comm::connection
xotcl::comm::dav
xotcl::comm::ftp
xotcl::comm::httpAccess
xotcl::comm::httpd
xotcl::comm::imap
xotcl::comm::ldap
xotcl::comm::mime
xotcl::comm::pcache
xotcl::htmllib
xotcl::metadataAnalyzer
xotcl::mixinStrategy
xotcl::mos::agent
xotcl::mos::agentManagement
xotcl::mos::httpPlace
xotcl::mos::invoker
xotcl::mos::placeAccessControl
xotcl::mos::secureHttpPlace
xotcl::mos::sendStrategy
xotcl::mos::webObject
xotcl::package
xotcl::pattern::adapter
xotcl::pattern::chainOfResponsibility
xotcl::pattern::composite
xotcl::pattern::link
xotcl::pattern::manager
xotcl::pattern::observer
xotcl::pattern::onCalleeProxy
xotcl::pattern::singleton
xotcl::pattern::sortedCompositeWithAfter
xotcl::rdf::parser
xotcl::rdf::recreatorVisitor
xotcl::rdf::triple
xotcl::rdf::tripleRecreator
xotcl::registry::registry
xotcl::script
xotcl::scriptCreation::recoveryPoint
xotcl::scriptCreation::scriptCreator
xotcl::scriptCreation::serializer
xotcl::staticMetadataAnalyzer
xotcl::store
xotcl::store::gdbm
xotcl::store::jufgdbm
xotcl::store::mem
xotcl::store::persistence
xotcl::store::sdbm
xotcl::store::tclgdbm
xotcl::store::textfile
xotcl::store::trace
xotcl::trace
xotcl::wafecompat
xotcl::xml::parser
xotcl::xml::printVisitor
xotcl::xml::recreatorVisitor
xotcl::xodoc}]
}
