IDE::DocGeneratorMain instproc pageContent {} {
  return {<html>
<title>[my getTitle]</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="docu.css">
<body>
<big>[my getTitle]</big>
Components:
<ul>
[my componentsList]
</ul>
Generated by [my getUserName]<br>
Generated on [clock format [clock seconds]]
</body>
</html>
}
}
