IDE::Deployer instproc startScriptInvocation {} {
    my instvar onefile nopackages isXOTclcode
    set script {#!/usr/local/bin/tcl
# File generated by xotclIDE
# edit if you want
}

    if {$isXOTclcode} {
        append script {package require XOTcl
namespace import xotcl::*
}
}

    append script {# we set variable progdir to script location
set sname [info script]
if {$sname eq ""} {
    # Run interactive for develop purposes
    set progdir [pwd]
} else {
    file lstat $sname stats
    # follow sym links
    if {$stats(type) eq "link"} {
        set sname [file readlink $sname]
        if {[file pathtype $sname] eq "relative"} {
            set sname [file join [file dirname [info script]] $sname]
        }
    }
    set progdir [file dirname $sname]
}
}
   if {!$nopackages && !$onefile} {
      append script {lappend auto_path [file dirname $progdir]} \n
   }
   return $script
}
