POTHelper instproc saveCatalogAsPot {{fileName {}}} {
    if {$fileName eq ""} {
         set types {{"POT catalog" .pot}}
         set fileName [IDE::Dialog getSaveFile {} $types .pot]
    }
    if {$fileName eq ""} return
    my instvar catalog
    set f [open $fileName w]
    puts $f "# POT File generated by TclSqueak Internationalization Helper PlugIn"
    foreach str $catalog {
        puts $f "msgid \"$str\""
        puts $f {msgstr ""}
    }
    close $f
}
